# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2671e22bb2297cff7df60c8500f0ef8868dbb033b91adc163a1408aace3e810624438bb622081c33c22a7129122eff99db87478f48827dbe2d008edcb72e9ab5

test:
  secret_key_base: f4b69250e7a8f6a41d9da018090f6f398f968a0a8c1cba82cf15b30d29333583f3c58b44d27353ea3afc9109780754ff783d8d191259b48c9b3a441d74be49ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
